name: HealthTrack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Iniciar Flask en segundo plano
        run: |
          nohup flask run --host=127.0.0.1 --port=5000 & sleep 12

      - name: Ejecutar pruebas unitarias
        run: |
          pytest tests/test_usuario.py

      - name: Ejecutar pruebas funcionales con Selenium
        run: |
          pytest tests/test_func_usuario2.py

      - name: Mostrar logs Flask (para debug)
        if: failure()
        run: cat flask.log